[masters]
master1 ansible_host=34.229.122.170
master2 ansible_host=54.152.61.153
master3 ansible_host=54.164.137.198

[workers]
worker1 ansible_host=98.94.58.124
worker2 ansible_host=3.93.191.246
worker3 ansible_host=18.208.189.182

[k8s:children]
masters
workers

[k8s:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=inventory/k8s-cluster-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'