[masters]
master1 ansible_host=<master-ip-1>
master2 ansible_host=<master-ip-2>
master3 ansible_host=<master-ip-3>

[workers]
worker1 ansible_host=<worker-ip-1>
worker2 ansible_host=<worker-ip-2>
worker3 ansible_host=<worker-ip-3>

[k8s:children]
masters
workers

[k8s:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=<path-to-your-private-key>.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'