---
- name: Add Kubernetes yum repository
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Kubernetes binaries
  yum:
    name:
      - "kubelet-{{ k8s_version_rpm }}"
      - "kubeadm-{{ k8s_version_rpm }}"
      - "kubectl-{{ k8s_version_rpm }}"
    state: present
    disable_excludes: kubernetes

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
