---
- name: Install dependencies (Debian/Ubuntu)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install dependencies (RHEL/CentOS)
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - curl
    state: present
  when: ansible_os_family == "RedHat"
