---
- name: Disable swap immediately
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: false

- name: Remove swap from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
